apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-x4s3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-x4s3
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-x4s3
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-x4s3
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-x4s3
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-omrz-tenant/rhtap-demo-app/hacbs-test-project-x4s3@sha256:aff77cfaf30e0043eaf787ac426bae28d1fe2fe39f9633a17cf590cf25a20152
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
